# Spring Datasource
spring.datasource.url=jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JDBC
spring.datasource.initialization-mode=always

# Logging
logging.level.org.springframework=INFO
